version: '3'

services:

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 4nRuZR4sRNlXi7v5LhrlNG9IW5c2IA2L1u5CUY
      POSTGRES_USER: wishlist
      POSTGRES_DB: wishlist