
server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:test}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      batch_size: 25
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver

clients:
  products:
    url: http://challenge-api.luizalabs.com
